[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test-pythonlibs-gpu"
version = "0.1.0"
requires-python = ">= 3.12"

dependencies = [
    "jax[cuda]>=0.5.0",
    "torch>=2.6.0",
]
